### ISSUE TITLE
Store text-to-image data for every image posted in the chat

### ISSUE THREAD

**Issue by exciteabletom** [openedtech/edubot#11]
This should allow the bot to have an "interpretation" of images it sends and join in on discussions about images.

**Comment by moodler** [comment]
Some possible tools that might provide an API https://www.futuretools.io/?tags-n5zn=image-scanning

**Comment by exciteabletom** [comment]
https://huggingface.co/Salesforce/blip2-opt-2.7b

**Comment by moodler** [comment]
https://replicate.com/pharmapsychotic/clip-interrogator

**Comment by moodler** [comment]
My tests didn't work :)

**Comment by NextGenOER** [comment]
Indeed!
