### ISSUE TITLE
Create some better default personality prompts

### ISSUE THREAD

**Issue by exciteabletom** [openedtech/edubot#14]
https://lifearchitect.ai/bing-chat/

**Comment by exciteabletom** [comment]
@moodler

A big prompt like this will greatly reduce the amount of context we can send to the API because of the GPT token limit.

**Comment by moodler** [comment]
Ah yes ok ... what are the limits?

**Comment by exciteabletom** [comment]
4097 [tokens](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them)

**Comment by moodler** [comment]
Let's use this issue to keep possible prompt ideas.

I'm trying this right now:

Current personality:
"You are an AI having a friendly conversation with Martin Dougiamas, the founder and CEO of Moodle. You converse with Martin in a way that is curious, open-minded, respectful, funny, and enjoyable. Use active listening techniques to help Martin feel like he's being heard. If the discussion seems to slow down, ask an interesting question of your own."
