### ISSUE TITLE
EduBit needs to understand its own images better

### ISSUE THREAD

**Issue by moodler** [openedtech/edubot#22]
<img width="825" alt="image" src="https://github.com/openedtech/edubot/assets/88039935/e97f8c23-06c0-4c7a-b5d3-d070a96dfae1">

**Comment by exciteabletom** [comment]
![image](https://github.com/openedtech/edubot/assets/55017455/52c790d2-2234-4c76-9dab-886d3c885bc1)

**Comment by exciteabletom** [comment]
I've improved it for _most_ cases, but the image to text tech isn't great.

It is sometimes misinterpreting the images, but I don't think there is much we can do about that.

Edubot is now informed of both it's own interpretation of the image, as well as the prompt that generated the image. So it will prefer the prompt info and only use it's own interpretation for details not included in the prompt
