### ISSUE TITLE
Regression: Edubot is replying with empty strings

### ISSUE THREAD

**Issue by moodler** [openedtech/edubot#25]
Something broke in your last changes this week ...  a lot of the replies are just empty strings:

{
  "content": {
    "body": "",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1689046670831,
  "sender": "@edubot:matrix.org",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$Cr5QKINKQU9YQXz-dcLNRDPQu8H5AmpPKgytLMLi_GQ",
  "room_id": "!NQkzhMsgIguVvQSzvU:openedtech.global"
}

**Comment by exciteabletom** [comment]
Occurred when tokens in prompt exceeded limit. Should be fixed with langchain refactor #9
